In [1]:
import pandas as pd
import numpy as np
import time 


def martrix_gen(n):
    '''
    Generate a martrix with n rows and n columns
    '''
    return np.random.rand(n,n)

0

def matrix_mult(m1,m2):
    '''
    Multiply two martrix
    '''
    return np.dot(m1,m2)

Matrix_A = martrix_gen(100)
Matrix_B = martrix_gen(100)
Product_matrix = matrix_mult(Matrix_A,Matrix_B)



def matrix_inverse(m):
    '''
    Inverse martrix
    '''
    return np.linalg.inv(m)


write_Product_matrix_to_csv = pd.DataFrame(Product_matrix)
# write_Product_matrix_to_csv.to_csv("Product_matrix.csv")


print (Matrix_A)
print ('\n')
print (Matrix_B)
print ('\n')
print (Product_matrix)
print ('\n')
print (matrix_inverse(Product_matrix))
print ('\n')




[[0.71181182 0.58450839 0.23162822 ... 0.40346372 0.52250756 0.84100449]
 [0.83820853 0.82273982 0.47953426 ... 0.35570183 0.92062335 0.52821345]
 [0.73148342 0.06801671 0.69276677 ... 0.59152429 0.46802768 0.41710366]
 ...
 [0.72021095 0.38585308 0.93700289 ... 0.09724025 0.02063146 0.94104292]
 [0.60924736 0.41748892 0.80760243 ... 0.65488143 0.246702   0.3945395 ]
 [0.06016351 0.18465682 0.95013021 ... 0.13011955 0.54630341 0.03208905]]


[[0.72497586 0.4882474  0.32133698 ... 0.90104286 0.86572068 0.46723359]
 [0.60369086 0.97465408 0.71227291 ... 0.60797577 0.15226035 0.86112801]
 [0.94476455 0.66259096 0.93256493 ... 0.66507371 0.07355873 0.7910604 ]
 ...
 [0.6974414  0.69485555 0.745912   ... 0.76913908 0.80315106 0.33023886]
 [0.91513128 0.91744282 0.32140713 ... 0.5484923  0.416594   0.78630524]
 [0.48959099 0.12082197 0.07295444 ... 0.68054161 0.53027858 0.96210681]]


[[25.03867098 22.52736826 25.69646772 ... 24.19024555 25.61715345
  27.38373089]
 [25.52208247 25.00160909 2