In [8]:
import pandas as pd
import numpy as np
import time 


def martrix_gen(n):
    '''
    Generate a martrix with n rows and n columns
    '''
    return np.random.rand(n,n)



def matrix_mult(m1,m2):
    '''
    Multiply two martrix
    '''
    return np.dot(m1,m2)

Matrix_A = martrix_gen(2)
Matrix_B = martrix_gen(2)
Product_matrix = matrix_mult(Matrix_A,Matrix_B)



def matrix_inverse(m):
    '''
    Inverse martrix
    '''
    return np.linalg.inv(m)


write_Product_matrix_to_csv = pd.DataFrame(Product_matrix)
# write_Product_matrix_to_csv.to_csv("Product_matrix.csv")


print (Matrix_A)
print ('\n')
print (Matrix_B)
print ('\n')
print (Product_matrix)
print ('\n')
print (matrix_inverse(Product_matrix))
print ('\n')




[[0.64284272 0.75507752]
 [0.42537044 0.25492422]]


[[0.4163591  0.35732466]
 [0.35278799 0.99198451]]


[[0.5340357  0.97872876]
 [0.26704105 0.40487622]]


[[ -8.96886681  21.68091746]
 [  5.91552562 -11.83002317]]




In [9]:
# display the two martrix


# display the product martrix
df_1 = pd.DataFrame(Product_matrix)
df_2 = pd.DataFrame(matrix_inverse(Product_matrix))

df_1.head()


0         1
0  0.534036  0.978729
1  0.267041  0.404876

In [10]:
df_2.head()

0          1
0 -8.968867  21.680917
1  5.915526 -11.830023