In [9]:
import numpy as np
import pandas as pd



matrix_a = np.random.randint(0,10,(4,4))

matrix_b = np.random.randint(0,10,(4,4))



def matrix_multiplction_n_times(matrix_a, matrix_b):
    A_time_B = np.dot(matrix_a, matrix_b)
    return A_time_B


A_time_B = matrix_multiplction_n_times(matrix_a, matrix_b)





def inverse_matrix():
    matrix_A_inverse = np.linalg.inv(matrix_a)

    return matrix_A_inverse


matrix_A_inverse= inverse_matrix()

proof_of_inverse = matrix_A_inverse.dot(matrix_a)


# wite the proof to txt file


print (proof_of_inverse)

[[ 1.00000000e+00  6.66133815e-16  4.44089210e-16  1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00  2.22044605e-16 -1.11022302e-16]
 [-3.33066907e-16 -1.11022302e-16  1.00000000e+00  1.11022302e-16]
 [ 2.77555756e-17  1.94289029e-16  0.00000000e+00  1.00000000e+00]]
